

**Lyushen Song**

# EDA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/assign2data.csv')

In [ ]:
df.head()

,ObsNum,TrainTest,DayOfWeek,Month,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),VolStock5(t-1),VolStock6(t-1)
0,1,Train,Monday,3,2.65,0,0,0,2.55,4.01,3.89,2.77,6.30,5.01
1,2,Train,Tuesday,3,3.99,0,0,0,2.65,2.18,2.74,1.81,4.29,3.02
2,3,Train,Wednesday,3,3.08,0,0,0,3.99,5.00,4.68,4.47,6.82,4.99
3,4,Train,Thursday,3,2.55,0,0,0,3.08,4.51,3.22,2.89,4.82,3.99
4,5,Train,Friday,3,2.56,0,0,0,2.55,3.80,2.60,3.40,4.62,4.01

In [ ]:
#check for null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ObsNum          753 non-null    int64
 1   TrainTest       753 non-null    object
 2   DayOfWeek       753 non-null    object
 3   Month           753 non-null    int64
 4   VolStock1(t)    503 non-null    float64
 5   EADay           753 non-null    int64
 6   EADayBefore     753 non-null    int64
 7   EADayAfter      753 non-null    int64
 8   VolStock1(t-1)  504 non-null    float64
 9   VolStock2(t-1)  753 non-null    float64
 10  VolStock3(t-1)  753 non-null    float64
 11  VolStock4(t-1)  753 non-null    float64
 12  VolStock5(t-1)  753 non-null    float64
 13  VolStock6(t-1)  753 non-null    float64
dtypes: float64(7), int64(5), object(2)
memory usage: 82.5+ KB

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoded_cols = encoder.fit_transform(df[['Month', 'DayOfWeek']]).toarray()

encoded_df = pd.DataFrame(encoded_cols, columns=encoder.get_feature_names_out(['Month', 'DayOfWeek']))

all_data_encoded = df.drop(['Month', 'DayOfWeek'], axis=1).reset_index(drop=True)
df = pd.concat([all_data_encoded, encoded_df], axis=1)
df

,ObsNum,TrainTest,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),...,Month_10,Month_11,Month_12,Month_13,Month_14,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,1,Train,2.65,0,0,0,2.55,4.01,3.89,2.77,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,Train,3.99,0,0,0,2.65,2.18,2.74,1.81,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3,Train,3.08,0,0,0,3.99,5.00,4.68,4.47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,Train,2.55,0,0,0,3.08,4.51,3.22,2.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5,Train,2.56,0,0,0,2.55,3.80,2.60,3.40,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,749,Test,NaN,0,0,0,NaN,3.35,2.34,2.14,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
749,750,Test,NaN,0,0,0,NaN,2.12,1.76,1.80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
750,751,Test,NaN,0,0,0,NaN,2.47,2.22,2.40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
751,752,Test,NaN,0,0,0,NaN,2.04,1.49,2.15,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
752,753,Test,NaN,0,0,0,NaN,2.37,2.39,2.72,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

I used OneHotEncoder to deal with categorical values such as day of the week and month of the week. And I also dropped 'Month', 'DayOfWeek' after transforming.

In [ ]:
df['TrainTest'].value_counts()

Train             252
Train/Validate    251
Test              250
Name: TrainTest, dtype: int64

In [ ]:
df_test=df[df['TrainTest']=='Test']

In [ ]:
df_test

,ObsNum,TrainTest,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),...,Month_10,Month_11,Month_12,Month_13,Month_14,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
503,504,Test,NaN,0,0,0,2.86,3.57,5.89,6.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
504,505,Test,NaN,0,0,0,NaN,4.42,8.15,5.98,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
505,506,Test,NaN,0,0,0,NaN,3.45,7.26,4.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
506,507,Test,NaN,0,0,0,NaN,5.27,7.80,5.07,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
507,508,Test,NaN,0,0,0,NaN,3.67,5.91,4.90,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,749,Test,NaN,0,0,0,NaN,3.35,2.34,2.14,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
749,750,Test,NaN,0,0,0,NaN,2.12,1.76,1.80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
750,751,Test,NaN,0,0,0,NaN,2.47,2.22,2.40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
751,752,Test,NaN,0,0,0,NaN,2.04,1.49,2.15,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
752,753,Test,NaN,0,0,0,NaN,2.37,2.39,2.72,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
df_train = df[df['TrainTest'].isin(['Train', 'Train/Validate'])]
df_train

,ObsNum,TrainTest,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),...,Month_10,Month_11,Month_12,Month_13,Month_14,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,1,Train,2.65,0,0,0,2.55,4.01,3.89,2.77,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,Train,3.99,0,0,0,2.65,2.18,2.74,1.81,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3,Train,3.08,0,0,0,3.99,5.00,4.68,4.47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,Train,2.55,0,0,0,3.08,4.51,3.22,2.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5,Train,2.56,0,0,0,2.55,3.80,2.60,3.40,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,Train/Validate,1.86,0,0,0,2.37,2.92,3.70,3.27,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
499,500,Train/Validate,1.94,0,0,0,1.86,2.55,5.04,3.93,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
500,501,Train/Validate,2.20,0,0,0,1.94,2.47,5.22,3.60,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
501,502,Train/Validate,2.44,0,0,0,2.20,2.96,8.36,4.11,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
502,503,Train/Validate,2.86,0,0,0,2.44,3.04,6.59,3.60,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

I decided to use all train and train/validate data as my 'training data'. Later, you can find me using train_test split to split into train and test data.

In [ ]:
df_train.columns

Index(['ObsNum', 'TrainTest', 'VolStock1(t)', 'EADay', 'EADayBefore',
       'EADayAfter', 'VolStock1(t-1)', 'VolStock2(t-1)', 'VolStock3(t-1)',
       'VolStock4(t-1)', 'VolStock5(t-1)', 'VolStock6(t-1)', 'Month_3',
       'Month_4', 'Month_5', 'Month_6', 'Month_7', 'Month_8', 'Month_9',
       'Month_10', 'Month_11', 'Month_12', 'Month_13', 'Month_14',
       'DayOfWeek_Friday', 'DayOfWeek_Monday', 'DayOfWeek_Thursday',
       'DayOfWeek_Tuesday', 'DayOfWeek_Wednesday'],
      dtype='object')

# Linear Regression and Random Forrest Model

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error

y = df_train['VolStock1(t)']
X = df_train[['EADay', 'EADayBefore',
       'EADayAfter', 'VolStock2(t-1)', 'VolStock3(t-1)',
       'VolStock4(t-1)', 'VolStock5(t-1)', 'VolStock6(t-1)', 'Month_3',
       'Month_4', 'Month_5', 'Month_6', 'Month_7', 'Month_8', 'Month_9',
       'Month_10', 'Month_11', 'Month_12', 'Month_13', 'Month_14',
       'DayOfWeek_Friday', 'DayOfWeek_Monday', 'DayOfWeek_Thursday',
       'DayOfWeek_Tuesday', 'DayOfWeek_Wednesday']]

# Split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#random linear regression model
lf_model = LinearRegression()
#use cross validation method to improve accuracy
cv_scores = cross_val_score(lf_model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')


lf_model.fit(X_train, y_train)

# predict on the test set
y_pred = lf_model.predict(X_test)

# Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE) on test set:", mse)

Mean Squared Error (MSE) on test set: 0.5087056602864183

Right off the bat, because I have used cross_validation to improve the model's accuracy, therefore, MSE for linear regression is quite good.

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error



#  Random Forest Regression model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
cv_scores = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

# Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE) on test set:", mse)

Mean Squared Error (MSE) on test set: 0.6350297673267331

For random Forest mode, the MSE is slightly higher, so I decided to use Hyperparameter tuning to achieve better performance.

# Hyperparameter Tuning For Random Forrest

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
param_grid = {
    'n_estimators': [10, 50, 100],  # Number of trees in the forest
    'min_samples_split': [2, 5, 10],   # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]      # Minimum number of samples required to be at a leaf node
}

# use Grid Search Cross Validation
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')

#  Grid Search
grid_search.fit(X_train, y_train)

# find best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# find best hyperparameters for Random Forest Regression model
best_rf_model = RandomForestRegressor(**best_params, random_state=42)

# fit the model
best_rf_model.fit(X_train, y_train)

y_pred = best_rf_model.predict(X_test)

#  Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE) on test set:", mse)

Best Hyperparameters: {'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 100}
Mean Squared Error (MSE) on test set: 0.5782945010261755

I find the best hyperparameters for Random Forest, therefore, I will use these best hyperparameters to fit into my model again.

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error



# fit the Random Forest Regression model with the best hyperparameters
rf_model = RandomForestRegressor(n_estimators=100, random_state=42,min_samples_leaf= 2,min_samples_split= 10 )
cv_scores = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

#  Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE) on test set:", mse)

Mean Squared Error (MSE) on test set: 0.5782945010261755

After using the best parameters, I can see a much improvement with the MSE for the Random Forest model.

#ARIMA Model

In [ ]:
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data = df_train['VolStock1(t)']

# Calculate the moving average
window_size = 5  # Adjust as needed
moving_avg = data.rolling(window=window_size).mean()

# Use the moving average as the univariate time series data
# For ARIMA, we usually need a univariate time series, so let's use the moving average as our target variable
data = moving_avg

# Split the data into train and test sets
train_size = int(len(data) * 0.8)
train, test = data[0:train_size], data[train_size:]

# Specify the order (p, d, q) of the ARIMA model. You may need to tune these parameters based on the characteristics of your data.
order = (1, 0, 1)  # Adjust as needed
arima_model = ARIMA(train, order=order)

# Fit the ARIMA model
arima_result = arima_model.fit()

# Forecast future values
forecast = arima_result.forecast(steps=len(test))

# Calculate Mean Squared Error
mse = mean_squared_error(test, forecast)
print("Mean Squared Error (MSE) on test set:", mse)

Mean Squared Error (MSE) on test set: 0.500954094018523

I also try to use the AMIRA model to count for time series, but I have only be able to do it with the help from chatgpt and looking at youtube, therefore, I am not quite sure about how does AMIRA works. And the stacking model performed better anyway, so I did not use AMIRA model for the final prediction.

# Stacking Method

In [ ]:
#reference: https://rasbt.github.io/mlxtend/user_guide/regressor/StackingRegressor/
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# define base estimators
base_estimators = [
    ('lr', LinearRegression()),
    ('rf', RandomForestRegressor(n_estimators=100, random_state=42,min_samples_leaf= 2,min_samples_split= 10 ))
]

# define meta-regressor
meta_regressor = LinearRegression()

#  StackingRegressor
stacked_model = StackingRegressor(estimators=base_estimators, final_estimator=meta_regressor)

# fit the StackingRegressor
stacked_model.fit(X_train, y_train)

# predict on the test set
y_pred_stacked = stacked_model.predict(X_test)

#  Mean Squared Error (MSE)
mse_stacked = mean_squared_error(y_test, y_pred_stacked)
print("Stacking Mean Squared Error (MSE) on test set:", mse_stacked)

Stacking Mean Squared Error (MSE) on test set: 0.4773032285781983

I decided to use a stacking method to compile two models I have used, and I used linear regression as my meta model because its performance is better than the tuned random forest model. I did get a very low MSE. Therefore, this is the final model I will be using for the final prediction.

# Using stacking model to predict the stock volume

In [ ]:
# Extract features for prediction (excluding the target column 'VolStock1(t)')

X_nan_predict = df_test[['EADay', 'EADayBefore',
       'EADayAfter', 'VolStock2(t-1)', 'VolStock3(t-1)',
       'VolStock4(t-1)', 'VolStock5(t-1)', 'VolStock6(t-1)', 'Month_3',
       'Month_4', 'Month_5', 'Month_6', 'Month_7', 'Month_8', 'Month_9',
       'Month_10', 'Month_11', 'Month_12', 'Month_13', 'Month_14',
       'DayOfWeek_Friday', 'DayOfWeek_Monday', 'DayOfWeek_Thursday',
       'DayOfWeek_Tuesday', 'DayOfWeek_Wednesday']]

# Use your trained model to predict the NaN values
predicted_values = stacked_model.predict(X_nan_predict)

# Replace NaN values in the original DataFrame with predicted values
df_test['VolStock1(t)'] = np.where(df_test['VolStock1(t)'].isnull(), predicted_values, df_test['VolStock1(t)'])

<ipython-input-52-9c435bb770c1>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['VolStock1(t)'] = np.where(df_test['VolStock1(t)'].isnull(), predicted_values, df_test['VolStock1(t)'])

In [ ]:
df_test['VolStock1(t-1)'] = df_test['VolStock1(t)'].shift(1)

<ipython-input-53-f0deef5590a1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['VolStock1(t-1)'] = df_test['VolStock1(t)'].shift(1)

In [ ]:
df_test.at[503, 'VolStock1(t-1)'] = df.at[502, 'VolStock1(t)']

Because VolStock1(t-1) is the stock volume for  yesterday's volume of stock1, I used a shift function to write all VolStock1(t-1) with yesterday's prediction data from 'VolStock1(t)' column.

In [ ]:
df_test

,ObsNum,TrainTest,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),...,Month_10,Month_11,Month_12,Month_13,Month_14,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
503,504,Test,3.369669,0,0,0,2.860000,3.57,5.89,6.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
504,505,Test,3.301931,0,0,0,3.369669,4.42,8.15,5.98,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
505,506,Test,2.948913,0,0,0,3.301931,3.45,7.26,4.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
506,507,Test,3.540945,0,0,0,2.948913,5.27,7.80,5.07,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
507,508,Test,2.669942,0,0,0,3.540945,3.67,5.91,4.90,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,749,Test,2.475526,0,0,0,2.484056,3.35,2.34,2.14,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
749,750,Test,2.223405,0,0,0,2.475526,2.12,1.76,1.80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
750,751,Test,2.370163,0,0,0,2.223405,2.47,2.22,2.40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
751,752,Test,2.312446,0,0,0,2.370163,2.04,1.49,2.15,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
752,753,Test,2.343595,0,0,0,2.312446,2.37,2.39,2.72,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
df.loc[503:752, :] = df_test.loc[503:752, :]
# I used loc function to replace df_test into the df.

In [ ]:
df

,ObsNum,TrainTest,VolStock1(t),EADay,EADayBefore,EADayAfter,VolStock1(t-1),VolStock2(t-1),VolStock3(t-1),VolStock4(t-1),...,Month_10,Month_11,Month_12,Month_13,Month_14,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,1,Train,2.650000,0,0,0,2.550000,4.01,3.89,2.77,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,Train,3.990000,0,0,0,2.650000,2.18,2.74,1.81,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3,Train,3.080000,0,0,0,3.990000,5.00,4.68,4.47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,Train,2.550000,0,0,0,3.080000,4.51,3.22,2.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5,Train,2.560000,0,0,0,2.550000,3.80,2.60,3.40,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,749,Test,2.475526,0,0,0,2.484056,3.35,2.34,2.14,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
749,750,Test,2.223405,0,0,0,2.475526,2.12,1.76,1.80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
750,751,Test,2.370163,0,0,0,2.223405,2.47,2.22,2.40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
751,752,Test,2.312446,0,0,0,2.370163,2.04,1.49,2.15,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
752,753,Test,2.343595,0,0,0,2.312446,2.37,2.39,2.72,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
df.to_csv('Assigment2 modified Lyushen Song.csv', index=False)

Lastly, what I have here is the final prediction for the test data using the stacking model.

# Reference

For the assigment, I have used the chatgpt to help me to save the model and to predict the stock volume data for the test. I also use chatgpt to help me to build my AMIRA model, though I did not use AMIRA model as my final predicting model. I also use the website of https://rasbt.github.io/mlxtend/user_guide/regressor/StackingRegressor/ to figure out how to use stackingregressor for my two models.